import Navbar from "@/components/Navbar";
import PhotoFeed from "@/components/PhotoFeed";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Photo feed App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
     <Navbar />

  <PhotoFeed />
        
        {children}</body>
    </html>
  );
}
